// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eBankingAPI.Data;

namespace eBankingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eBankingAPI.Data.Models.Account", b =>
                {
                    b.Property<int>("AcnumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Aod")
                        .HasColumnType("datetime2");

                    b.Property<string>("Astatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Atype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BId")
                        .HasColumnType("int");

                    b.Property<int>("CustId")
                        .HasColumnType("int");

                    b.Property<decimal>("Opening_balance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AcnumberId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("eBankingAPI.Data.Models.Branch", b =>
                {
                    b.Property<int>("BId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bcity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BId");

                    b.ToTable("Branchs");
                });

            modelBuilder.Entity("eBankingAPI.Data.Models.Customer", b =>
                {
                    b.Property<int>("CustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ltname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobileno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("eBankingAPI.Data.Models.Loan", b =>
                {
                    b.Property<string>("LoanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Bid")
                        .HasColumnType("int");

                    b.Property<int>("Custid")
                        .HasColumnType("int");

                    b.Property<decimal>("Loan_amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LoanId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("eBankingAPI.Data.Models.Trandetail", b =>
                {
                    b.Property<string>("TnumberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AcnumberId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dot")
                        .HasColumnType("datetime2");

                    b.Property<string>("Medium_of_transaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Transaction_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Transaction_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TnumberId");

                    b.ToTable("Trandetails");
                });
#pragma warning restore 612, 618
        }
    }
}
